name: Lint Spelling

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  spelling-lint:
    name: Check Spelling
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-files: |
            pyproject.toml
            uv.lock
          uv-version: "0.8.3"
      
      - name: Setup Python
        run: uv python install
      
      - name: Run codespell
        run: uv run --group lint codespell README.md docs/ src/ tests/ --ignore-words-list=egocentric,ego4d,ego4dconsortium,ego4dconsortiumsharing,ego4dconsortiumsharingpublic,ego4dconsortiumsharingpublicv2,ego4dconsortiumsharingpublicv2ego4d.json,ego4dconsortiumsharingpublicv2ego4d.jsons3,ego4dconsortiumsharingpublicv2ego4d.jsons3://ego4d-consortium-sharing/public/v2/ego4d.json,ego4dconsortiumsharingpublicv2ego4d.jsons3://ego4d-consortium-sharing/public/v2/ego4d
